---
name: mvn
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: mvn-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mvn:
    name: mvn
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: mvn clean install --errors --batch-mode
